services:
  localstack-dynamodb:
    image: localstack/localstack:latest
    container_name: localstack_kms_example_dynamodb
    ports:
      - "4566:4566" # LocalStack Gateway (Default Port)
      - "8000:8000" # DynamoDB
    environment:
      - SERVICES=dynamodb # 추가: DynamoDB 활성화
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_DEFAULT_REGION=ap-northeast-2
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack" # Persist LocalStack data
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for some advanced features
    networks:
      - aws-kms-example
  local-kms:
    image: nsmithuk/local-kms:latest
    container_name: local-kms_example_kms
    ports:
      - "4574:4574"
    environment:
      - PORT=4574
      - KMS_ACCOUNT_ID=000000000000
      - KMS_REGION=ap-northeast-2
    networks:
      - aws-kms-example

networks:
  aws-kms-example:
    driver: bridge