# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

build:
    maxIssues: 0

config:
    validation: true
    warningsAsErrors: false

output-reports:
    active: true
    exclude:
        - 'TxtOutputReport'
        - 'XmlOutputReport'

formatting:
    autoCorrect: true
    ArgumentListWrapping:
        active: false
    EnumEntryNameCase:
        active: false
    MaximumLineLength:
        maxLineLength: 160
    MultiLineIfElse:
        active: true
        autoCorrect: true
    ParameterListWrapping:
        active: true
        autoCorrect: true
        indentSize: 4
        maxLineLength: 160
    NoWildcardImports:
        active: false
    NoMultipleSpaces:
        active: true
        autoCorrect: false
    PropertyWrapping:
        active: false
    SpacingAroundUnaryOperator:
        active: true
        autoCorrect: true
    Wrapping:
        active: true
        maxLineLength: 160

style:
    DestructuringDeclarationWithTooManyEntries:
        active: true
        maxDestructuringEntries: 4
    MaxLineLength:
        active: false
        maxLineLength: 160
    ReturnCount:
        active: false
    WildcardImport:
        active: false
    MagicNumber:
        ignoreNamedArgument: true
        ignoreRanges: true
    ThrowsCount:
        active: false

complexity:
    LongParameterList:
        functionThreshold: 8
        constructorThreshold: 8
    ComplexCondition:
        threshold: 6
    TooManyFunctions:
        thresholdInClasses: 40
        thresholdInFiles: 100
        thresholdInObjects: 28
        thresholdInInterfaces: 12
    CyclomaticComplexMethod:
        threshold: 26
    LongMethod:
        threshold: 90

naming:
    excludes: "**/test/**,**/*.Test.kt"
    active: true
    BooleanPropertyNaming:
        active: true
    ConstructorParameterNaming:
        active: false
    NonBooleanPropertyPrefixedWithIs:
        active: true
    EnumNaming:
        active: false
    PackageNaming:
        active: false

performance:
    active: true
    SpreadOperator:
        active: false
